### PR TITLE
Matrix Support

### PR DESCRIPTION
**Pull request by 203Null**
Adding support for Matrix controller family

### CODE REVIEW

**Review by kimjisub — APPROVED** [review]
Thanks for your collaboration.

**Comment by 203Null** [comment]
Matrix is now renamed to Mystrix. I think the code still works, but if you ever update the app, can you change Matrix to Mystrix? 

Thank you!

**Comment by kimjisub** [comment]
@203Null Please update the relevant code and submit a PR; I’ll proceed with the app update once it’s merged. Thank you for your support.

**Comment by 203Null** [comment]
Got it. I will make a PR when I have time. I no longer have Android Studio etc so I will have to get them to verify the PR.

**Pull request merged**
